language: minimal

dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:plt/racket'
    packages:
      - racket

script:
  - raco pkg install --auto racket-doc
  - raco pkg install --auto
  - raco test .
