language: minimal

dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:plt/racket'
    update: true
    packages:
      - racket
      - racket-doc

script:
  - raco pkg install --auto
  - raco test .
